# Generated by Django 4.1.5 on 2024-05-12 03:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counts', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('product_feature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='features.productfeature')),
            ],
        ),
    ]
